# Generated by Django 2.1.15 on 2021-09-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='rates_number',
            new_name='avg_rating',
        ),
    ]
