# Generated by Django 2.1.15 on 2021-09-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(default='init', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='init', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='rates_number',
            field=models.IntegerField(default=0),
        ),
    ]
