# Generated by Django 2.1.15 on 2021-09-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210928_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='no_rating',
            field=models.IntegerField(default=0),
        ),
    ]
