# Generated by Django 2.1.15 on 2021-09-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_car_no_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='no_rating',
            new_name='rates_number',
        ),
    ]
